cmake_minimum_required(VERSION 3.16)

project(linux-system-monitor
    VERSION 0.1.0
    LANGUAGES CXX
)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(linux-system-monitor
    src/main.cpp
)

target_include_directories(linux-system-monitor
    PRIVATE
        ${PROJECT_SOURCE_DIR}/include
)